<?php
use app\Controllers\AuthController;
use app\Controllers\FormController;
?>

<section class="row change-password center-x">
  <form class="col g-row-1" method="POST" action="">
    <div class="row">
      <div class="col center-x">
        <h1 data-typo="h2">Change password</h1>
      </div>
    </div>

    <?= FormController::formAlerts() ?>

    <div class="row">
      <?php $this->component('form-input', [
          'id' => 'old-password',
          'label' => 'Old password',
          'required' => true,
          'icon' => 'key',
          'type' => 'password',
          'maxlength' => MAX_PASSWORD_LENGTH,
          'placeholder' => 'Enter old password:',
          'autocomplete' => 'current-password',
          'ariaLabel' => 'Old password input field',
          'error' => isset($_POST['submit']) && empty($_POST['old-password']),
          'capsLockWarning' => true,
      ]) ?>
    </div>

    <div class="row">
      <div class="col form-group g-row-0.25">
        <div class="row form-row g-1">
          <?php $this->component('form-input', [
              'id' => 'new-password',
              'label' => 'New password',
              'required' => true,
              'icon' => 'key',
              'type' => 'password',
              'maxlength' => MAX_PASSWORD_LENGTH,
              'placeholder' => 'Enter new password:',
              'autocomplete' => 'new-password',
              'ariaLabel' => 'New password input field',
              'error' => isset($_POST['submit']) && empty($_POST['new-password']),
              'capsLockWarning' => true,
              'inputClass' => 'input-password',
              'appendIcon' => 'eye password-toggle input-icon-clickable',
              'extraAttrs' => 'data-password-pattern="' . AuthController::getPasswordPatternSource() . '" data-password-message="' . AuthController::getPasswordRequirements() . '"',
          ]) ?>

          <?php $this->component('form-input', [
              'id' => 'new-password-check',
              'label' => 'Repeat new password',
              'required' => true,
              'icon' => 'key',
              'type' => 'password',
              'maxlength' => MAX_PASSWORD_LENGTH,
              'placeholder' => 'Repeat new password:',
              'autocomplete' => 'new-password',
              'ariaLabel' => 'Repeat new password input field',
              'error' => isset($_POST['submit']) && empty($_POST['new-password-check']),
              'extraAttrs' => 'data-match="new-password"',
          ]) ?>
        </div>

        <?php $this->component('password-hint') ?>
      </div>
    </div>

    <div class="row g-2 center-x">
      <a class="col link lh-1 g-col-0.5 center-y f-0" href="<?= $this::prev() ?>"><i class="fas fa-arrow-left"></i>Back</a>
      <button class="col button g-col-0.5 center-y f-0" type="submit" name="submit" aria-label="Button to submit change password form"><i class="fas fa-lock"></i>Change password</button>
    </div>
  </form>
</section>
