<?php
use app\Controllers\FormController;
use app\Controllers\RequestController;
?>

<section class="row contact center-x">
  <form class="col g-row-1" method="POST" action="">
    <div class="row">
      <div class="col center-x">
        <h1 data-typo="h2">Contact</h1>
      </div>
    </div>

    <?= FormController::formAlerts() ?>

    <div class="row">
      <div class="col">
        <p>If you have any questions or need help, please feel free to contact us. Fill out the form below, and we will get back to you as soon as possible.</p>
      </div>
    </div>

    <div class="row">
      <?php $this->component('form-input', [
          'id' => 'name',
          'label' => 'Name',
          'required' => true,
          'icon' => 'user',
          'maxlength' => MAX_NAME_LENGTH,
          'placeholder' => 'Enter name:',
          'value' => RequestController::post('name') ?? '',
          'autocomplete' => 'name',
          'ariaLabel' => 'Name input field',
          'error' => isset($_POST['submit']) && empty($_POST['name']),
      ]) ?>
    </div>

    <div class="row">
      <?php $this->component('form-input', [
          'id' => 'email',
          'label' => 'Email',
          'required' => true,
          'icon' => 'at',
          'type' => 'email',
          'maxlength' => MAX_EMAIL_LENGTH,
          'placeholder' => 'Enter email:',
          'value' => RequestController::post('email') ?? '',
          'autocomplete' => 'email',
          'ariaLabel' => 'Email input field',
          'error' => isset($_POST['submit']) && empty($_POST['email']),
      ]) ?>
    </div>

    <div class="row">
      <?php $this->component('form-input', [
          'id' => 'subject',
          'label' => 'Subject',
          'required' => true,
          'icon' => 'heading',
          'maxlength' => MAX_CONTACT_SUBJECT_LENGTH,
          'placeholder' => 'Enter subject:',
          'value' => RequestController::post('subject') ?? '',
          'autocomplete' => 'off',
          'ariaLabel' => 'Subject input field',
          'error' => isset($_POST['submit']) && empty($_POST['subject']),
      ]) ?>
    </div>

    <div class="row">
      <div class="col form-group g-row-0.25">
        <div class="row">
          <label class="col" for="message">Message: <span class="required">*</span></label>
          <div class="col end-x end-y">
            <p class="form-link clear-message" inert>Clear</p>
          </div>
        </div>
        <div class="row input-group <?= (isset($_POST['submit']) && empty($_POST['message'])) ? 'error' : '' ?>">
          <div class="col input-prepend center f-0"><i class="fas fa-message"></i></div>
          <textarea class="col message-field" id="message" name="message" maxlength="<?= MAX_CONTACT_MESSAGE_LENGTH ?>" rows="5" placeholder="Enter message:" autocomplete="off" aria-label="Message input field"><?= RequestController::post('message') ?? '' ?></textarea>
        </div>
        <div class="row">
          <div class="col end-x">
            <p class="form-details message-warning"><span class="message-length">0</span>/<?= MAX_CONTACT_MESSAGE_LENGTH ?></p>
          </div>
        </div>
      </div>
    </div>

    <div class="row center-x">
      <button class="col button g-col-0.5 center-y f-0" type="submit" name="submit" aria-label="Button to submit the contact form"<?= $this->pageObj->cooldown > 0 ? ' data-timeout="' . $this->pageObj->cooldown . '" inert' : '' ?>><i class="fas fa-paper-plane"></i>Send</button>
    </div>
  </form>
</section>
