<?php
use app\Controllers\FormController;
use app\Controllers\RequestController;
?>

<section class="row forgot-password center-x">
  <form class="col g-row-1" method="POST" action="">
    <div class="row">
      <div class="col center-x">
        <h1 data-typo="h2">Forgot password</h1>
      </div>
    </div>

    <?= FormController::formAlerts() ?>

    <div class="row">
      <div class="col">
        <p class="form-details">In case you forgot your password, we can send you a link to reset it. Enter your email address below, and we'll send you a link to reset your password.</p>
      </div>
    </div>

    <div class="row">
      <?php $this->component('form-input', [
          'id' => 'email',
          'label' => 'Email',
          'required' => true,
          'icon' => 'at',
          'type' => 'email',
          'maxlength' => MAX_EMAIL_LENGTH,
          'placeholder' => 'Enter email:',
          'value' => RequestController::post('email') ?? '',
          'autocomplete' => 'email',
          'ariaLabel' => 'Email input field',
          'error' => isset($_POST['submit']) && empty($_POST['email']),
      ]) ?>
    </div>

    <div class="row">
      <div class="col">
        <p class="form-details">It may take a few minutes for the email to arrive. If you don't see it in your inbox, check your spam folder.</p>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <p class="form-details">Didn't receive an email? Please try again after 1 minute or contact an administrator.</p>
      </div>
    </div>

    <div class="row g-2 center-x">
      <a class="col link lh-1 g-col-0.5 center-y f-0" href="<?= $this::prev() ?>"><i class="fas fa-arrow-left"></i>Back</a>
      <button class="col button g-col-0.5 center-y f-0" type="submit" name="submit" aria-label="Button to submit the forgot password form"<?= $this->pageObj->cooldown > 0 ? ' data-timeout="' . $this->pageObj->cooldown . '" inert' : '' ?>><i class="fas fa-key"></i>Forgot password</button>
    </div>
  </form>
</section>
