<?php
use app\Controllers\AuthController;
use app\Controllers\FormController;
?>

<section class="row reset-password center-x">
  <form class="col g-row-1" method="POST" action="">
    <div class="row">
      <div class="col center-x">
        <h1 data-typo="h2">Reset password</h1>
      </div>
    </div>

    <?= FormController::formAlerts() ?>

    <div class="row">
      <?php $this->component('form-input', [
          'id' => 'new-password',
          'label' => 'New password',
          'required' => true,
          'icon' => 'key',
          'type' => 'password',
          'maxlength' => MAX_PASSWORD_LENGTH,
          'placeholder' => 'Enter new password:',
          'autocomplete' => 'new-password',
          'ariaLabel' => 'New password input field',
          'error' => isset($_POST['submit']) && empty($_POST['new-password']),
          'inert' => $this->pageObj->disableForm,
          'capsLockWarning' => true,
          'inputClass' => 'input-password',
          'appendIcon' => 'eye password-toggle input-icon-clickable',
          'extraAttrs' => 'data-password-pattern="' . AuthController::getPasswordPatternSource() . '" data-password-message="' . AuthController::getPasswordRequirements() . '"',
      ]) ?>
    </div>

    <div class="row">
      <?php $this->component('form-input', [
          'id' => 'new-password-check',
          'label' => 'Repeat new password',
          'required' => true,
          'icon' => 'key',
          'type' => 'password',
          'maxlength' => MAX_PASSWORD_LENGTH,
          'placeholder' => 'Repeat new password:',
          'autocomplete' => 'new-password',
          'ariaLabel' => 'Repeat new password input field',
          'error' => isset($_POST['submit']) && empty($_POST['new-password-check']),
          'inert' => $this->pageObj->disableForm,
          'extraAttrs' => 'data-match="new-password"',
      ]) ?>
    </div>

    <?php $this->component('password-hint') ?>

    <div class="row g-2 center-x">
      <button class="col button g-col-0.5 center-y f-0" type="submit" name="submit" aria-label="Button to submit reset password form" <?= $this->pageObj->disableForm ? 'inert' : '' ?>><i class="fas fa-lock"></i>Reset password</button>
    </div>
  </form>
</section>
