<?php
use app\Models\Url;
?>

<section class="row roles">
  <div class="col f-col g-row-2">
    <?php $this->component('breadcrumbs') ?>

    <div class="row">
      <div class="col center-x">
        <h1 data-typo="h2">Roles</h1>
      </div>
    </div>

    <div class="row center-x">
      <div class="col roles-table f-col g-row-1 w-100">

        <div class="row g-1">
          <div class="col end-x">
            <?php $this->component('column-toggle') ?>
          </div>
        </div>

        <div class="row table-container">
          <div class="col">
            <table class="data-table" data-table-id="roles" data-hidden-cols="<?= $this->pageObj->hiddenColumnsJson() ?>">
              <thead>
              <?= $this->pageObj->renderThead() ?>
              </thead>
              <tbody>
              <?= $this->pageObj->renderTbody() ?>
              </tbody>
            </table>
          </div>
        </div>

      </div>
    </div>

    <div class="row g-col-1 center-x">
      <a class="col button g-col-0.5 center-y f-0" href="<?= Url::to('admin/roles/create') ?>"><i class="fas fa-plus"></i>Create new role</a>
    </div>
  </div>
</section>

<?php $this->component('role-delete-modal') ?>
