<!-- Reset (load first) -->
<link rel="stylesheet" href="<?= $this->url('assets/the-new-css-reset/css/reset.css') ?>">

<!-- Fonts -->
<link rel="stylesheet" href="<?= $this->url('font/font.css') ?>">

<!-- Font Awesome -->
<link rel="stylesheet" href="<?= $this->url('assets/fontawesome/css/all.min.css') ?>">

<!-- Hamburgers -->
<link rel="stylesheet" href="<?= $this->url('assets/hamburgers/css/hamburgers.min.css') ?>">

<!-- Main (load last) -->
<link rel="stylesheet" href="<?= $this->url('css/main.min.css') ?>">
