<?php

use app\Models\Url;

?>

<!-- Reset (load first) -->
<link rel="stylesheet" href="<?= Url::file('assets/the-new-css-reset/css/reset.css') ?>">

<!-- Fonts -->
<link rel="stylesheet" href="<?= Url::file('font/font.css') ?>">

<!-- Font Awesome -->
<link rel="stylesheet" href="<?= Url::file('assets/fontawesome/css/all.min.css') ?>">

<!-- Hamburgers -->
<link rel="stylesheet" href="<?= Url::file('assets/hamburgers/css/hamburgers.min.css') ?>">

<!-- Main (load last) -->
<link rel="stylesheet" href="<?= Url::file('css/main.min.css') ?>">
