<!-- Reset (load first) -->
<link rel="stylesheet" href="<?= $this->url('css/reset.css') ?>">

<!-- Fonts -->
<link rel="stylesheet" href="<?= $this->url('font/font.css') ?>">

<!-- Font Awesome -->
<link rel="stylesheet" href="<?= $this->url('lib/font-awesome/icons/all.min.css') ?>">

<!-- Hamburgers -->
<link rel="stylesheet" href="<?= $this->url('lib/hamburgers/hamburgers.min.css') ?>">

<!-- Main (load last) -->
<link rel="stylesheet" href="<?= $this->url('css/main.min.css') ?>">
