<?php
use app\Controllers\FormController;
use app\Controllers\RequestController;
?>

<section class="row users center-x">
  <form class="col g-row-1" method="POST" action="" data-track-form>
    <?php $this->component('breadcrumbs') ?>

    <div class="row">
      <div class="col center-x">
        <h1 data-typo="h2">Create user</h1>
      </div>
    </div>

    <?= FormController::formAlerts() ?>

    <div class="row form-row g-1">
      <?php $this->component('form-input', [
          'id' => 'username',
          'label' => 'Username',
          'icon' => 'user',
          'maxlength' => MAX_USERNAME_LENGTH,
          'placeholder' => 'Enter username:',
          'value' => RequestController::post('username') ?? '',
      ]) ?>

      <div class="col form-group g-row-0.25">
        <div class="row">
          <label class="col" for="role">User role: <span class="required">*</span></label>
        </div>
        <div class="row input-group">
          <div class="col input-prepend center f-0"><i class="fas fa-user-group"></i></div>
          <select class="col" id="role" name="role">
            <?php foreach ($this->pageObj->availableRoles as $r) : ?>
              <option value="<?= $r['name'] ?>" <?= ($_POST['role'] ?? '') === $r['name'] ? 'selected' : '' ?>><?= $r['name'] ?></option>
            <?php endforeach ?>
          </select>
        </div>
      </div>
    </div>

    <div class="row form-row connected-row">
      <div class="row">
        <?php $this->component('form-input', [
            'id' => 'first_name',
            'label' => 'First name',
            'icon' => 'address-card',
            'maxlength' => MAX_NAME_LENGTH,
            'placeholder' => 'Enter first name:',
            'value' => RequestController::post('first_name') ?? '',
        ]) ?>
      </div>

      <?php $this->component('form-input', [
          'id' => 'last_name',
          'label' => 'Last name',
          'icon' => 'address-card',
          'maxlength' => MAX_NAME_LENGTH,
          'placeholder' => 'Enter last name:',
          'value' => RequestController::post('last_name') ?? '',
          'groupClass' => 'f-g-2',
      ]) ?>
    </div>

    <div class="row">
      <div class="col form-group g-row-0.25">
        <div class="row">
          <label class="col" for="email">Email: <span class="required">*</span></label>
        </div>
        <div class="row input-group <?= (isset($_POST['submit']) && empty($_POST['email'])) ? 'error' : '' ?>">
          <div class="col input-prepend center f-0"><i class="fas fa-at"></i></div>
          <input class="col" id="email" type="email" name="email" maxlength="<?= MAX_EMAIL_LENGTH ?>" placeholder="Enter email:" value="<?= RequestController::post('email') ?? '' ?>">
        </div>
        <div class="row">
          <div class="col">
            <p class="form-details">The user will be sent an email with information about the created account, as well as including the generated password. Which they will have to change upon first login.</p>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <?php $this->component('form-input', [
          'id' => 'password',
          'label' => 'Password',
          'required' => true,
          'icon' => 'key',
          'type' => 'text',
          'maxlength' => PASSWORD_CONFIG['generated_length'],
          'placeholder' => 'Enter password:',
          'value' => $this->pageObj->generatedPassword,
          'readonly' => true,
      ]) ?>
    </div>

    <div class="row g-2 center-x">
      <a class="col link lh-1 g-col-0.5 center-y f-0" href="<?= $this::prev() ?>"><i class="fas fa-arrow-left"></i>Back</a>
      <button class="col button create-user g-col-0.5 center-y f-0" type="submit" name="submit" inert><i class="fas fa-user-plus"></i>Create user</button>
    </div>
  </form>
</section>
