<?php
use app\Controllers\AuthController;
use app\Controllers\FormController;
use app\Controllers\RequestController;
use app\Controllers\SessionController;
?>

<?php if ($this->pageObj->user !== []) : ?>

  <?php if ($this->pageObj->user['id'] !== SessionController::get('user')['id']) : ?>

    <section class="row users center-x">
      <form class="col g-row-1" method="POST" action="" data-track-form>
        <?php $this->component('breadcrumbs') ?>

        <div class="row">
          <div class="col center-x">
            <h1 data-typo="h2">Edit user</h1>
          </div>
        </div>

        <?= FormController::formAlerts() ?>

        <div class="row form-row g-1">
          <?php $this->component('form-input', [
              'id' => 'id',
              'label' => 'Id',
              'icon' => 'hashtag',
              'type' => 'number',
              'value' => $this->pageObj->user['id'],
              'readonly' => true,
              'inert' => true,
          ]) ?>

          <?php $this->component('form-input', [
              'id' => 'last_update',
              'label' => 'Last update',
              'icon' => 'calendar-check',
              'value' => $this->pageObj->user['last_update'],
              'readonly' => true,
              'inert' => true,
          ]) ?>
        </div>

        <div class="row form-row g-1">
          <?php $this->component('form-input', [
              'id' => 'username',
              'label' => 'Username',
              'icon' => 'user',
              'maxlength' => MAX_USERNAME_LENGTH,
              'placeholder' => 'Enter username:',
              'value' => RequestController::post('username') ?? $this->pageObj->user['username'] ?? '',
          ]) ?>
        </div>

        <div class="row form-row connected-row">
          <div class="row">
            <?php $this->component('form-input', [
                'id' => 'first_name',
                'label' => 'First name',
                'icon' => 'address-card',
                'maxlength' => MAX_NAME_LENGTH,
                'placeholder' => 'Enter first name:',
                'value' => RequestController::post('first_name') ?? $this->pageObj->user['first_name'] ?? '',
            ]) ?>
          </div>

          <?php $this->component('form-input', [
              'id' => 'last_name',
              'label' => 'Last name',
              'icon' => 'address-card',
              'maxlength' => MAX_NAME_LENGTH,
              'placeholder' => 'Enter last name:',
              'value' => RequestController::post('last_name') ?? $this->pageObj->user['last_name'] ?? '',
              'groupClass' => 'f-g-2',
          ]) ?>
        </div>

        <div class="row">
          <?php $this->component('form-input', [
              'id' => 'email',
              'label' => 'Email',
              'required' => true,
              'icon' => 'at',
              'type' => 'email',
              'maxlength' => MAX_EMAIL_LENGTH,
              'placeholder' => 'Enter email:',
              'value' => RequestController::post('email') ?? $this->pageObj->user['email'] ?? '',
              'error' => isset($_POST['submit']) && empty($_POST['email']),
          ]) ?>
        </div>

        <div class="row form-row g-1">
          <div class="col form-group g-row-0.25">
            <div class="row">
              <label class="col" for="role">User role: <span class="required">*</span></label>
            </div>
            <div class="row input-group">
              <div class="col input-prepend center f-0"><i class="fas fa-user-group"></i></div>
              <select class="col edit-user-role" id="role" name="role">
                <?php foreach ($this->pageObj->availableRoles as $r) : ?>
                  <option value="<?= $r['name'] ?>" <?= ($_POST['role'] ?? $this->pageObj->user['role_name']) === $r['name'] ? 'selected' : '' ?>><?= $r['name'] ?></option>
                <?php endforeach ?>
              </select>
            </div>
          </div>

          <?php $this->component('form-input', [
              'id' => 'verified',
              'label' => 'Verified',
              'icon' => 'check',
              'value' => AuthController::isVerified($this->pageObj->user['id']) ? 'True' : 'False',
              'readonly' => true,
              'inert' => true,
          ]) ?>
        </div>

        <div class="row g-2 center-x">
          <a class="col link lh-1 g-col-0.5 center-y f-0" href="<?= $this::prev() ?>"><i class="fas fa-arrow-left"></i>Back</a>
          <button class="col button edit-user g-col-0.5 center-y f-0" type="submit" name="submit" inert><i class="fas fa-user-pen"></i>Edit user</button>
        </div>
      </form>
    </section>

  <?php else : ?>

    <section class="row users min-h-content center-y">
      <div class="col center-x">
        <h1 data-typo="h5">Cannot edit your own user.</h1>
      </div>
    </section>

  <?php endif ?>

<?php else : ?>

  <section class="row users min-h-content center-y">
    <div class="col center-x">
      <h1 data-typo="h5">Could not find user.</h1>
    </div>
  </section>

<?php endif ?>
