<?php
use app\Controllers\AlertController;
?>

</main>

<!-- Alert -->
<?php if (($alert = AlertController::pull()) !== null) : ?>
  <div class="alert <?= $alert['type'] ?? '' ?> global" role="alert"<?= $alert['timeout'] > 0 ? ' data-timeout="' . ($alert['timeout'] - time()) * 1000 . '"' : '' ?>>
    <?= $alert['message'] ?>
  </div>
<?php endif ?>

<!-- Footer -->
<?php $this->part('layout/footer') ?>

<!-- Cookie -->
<?php $this->part('layout/cookie') ?>

<!-- Scripts -->
<?php $this->part('index/js') ?>
</body>
</html>
