<?php
use app\Controllers\FormController;
use app\Controllers\RequestController;
?>

<section class="row roles center-x">
  <form class="col g-row-1" method="POST" action="" data-track-form>
    <?php $this->component('breadcrumbs') ?>

    <div class="row">
      <div class="col center-x">
        <h1 data-typo="h2">Create role</h1>
      </div>
    </div>

    <?= FormController::formAlerts() ?>

    <div class="row">
      <?php $this->component('form-input', [
          'id' => 'name',
          'label' => 'Name',
          'required' => true,
          'icon' => 'user-group',
          'maxlength' => MAX_ROLE_NAME_LENGTH,
          'placeholder' => 'Enter role name:',
          'value' => RequestController::post('name') ?? '',
          'error' => isset($_POST['submit']) && empty($_POST['name']),
      ]) ?>
    </div>

    <div class="row g-2 center-x">
      <a class="col link lh-1 g-col-0.5 center-y f-0" href="<?= $this::prev() ?>"><i class="fas fa-arrow-left"></i>Back</a>
      <button class="col button create-role g-col-0.5 center-y f-0" type="submit" name="submit" inert><i class="fas fa-plus"></i>Create role</button>
    </div>
  </form>
</section>
