<div class="row nav-list w-auto end-x f-0">
  <a class="col nav-item nav-link center f-0" href="<?= $this->url('contact') ?>" aria-label="Link to contact page">Contact</a>
  <?php if (isset($_SESSION['user']['id'])) : ?>
    <?php if ($_SESSION['user']['role'] == 1) : ?>
      <a class="col nav-item nav-button users center f-0" href="<?= $this->url('users') ?>" aria-label="Link to registered users overview">Users</a>
    <?php endif ?>
    <a class="col nav-item nav-link profile center f-0" href="<?= $this->url('profile') ?>" aria-label="Link to your profile"><i class="fas fa-circle-user"></i></a>
    <a class="col nav-item nav-button logout center f-0" href="<?= $this->url('logout') ?>" aria-label="Logout button"><i class="fas fa-right-from-bracket"></i> Logout</a>
  <?php else : ?>
    <a class="col nav-item nav-button center f-0" href="<?= $this->url('register') ?>" aria-label="Link to register page">Register</a>
    <a class="col nav-item nav-button login center f-0" href="<?= $this->url('login') ?>" aria-label="Link to login page"><i class="fas fa-right-to-bracket"></i> Login</a>
  <?php endif ?>
</div>
