<?php
use app\Controllers\AppController;
use app\Models\Url;

$redirectPage = AppController::sanitize($this->pageObj->redirectPage);
?>

<section class="row error min-h-content center-y">
  <div class="col f-col g-row-1">
    <div class="row">
      <div class="col center-x">
        <h1><?= $this->pageObj->code ?></h1>
      </div>
    </div>

    <div class="row">
      <div class="col f-col g-row-1">
        <div class="row">
          <div class="col center-x">
            <p data-typo="h3"><?= $this->pageObj->message ?></p>
          </div>
        </div>

        <div class="row">
          <div class="col center-x">
            <p>Click <a class="link underline" href="<?= Url::to($redirectPage) ?>" aria-label="Link to <?= $redirectPage ?> page">here</a> to go back to the <?= $redirectPage ?> page.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
