<section class="error min-h-content f-col g-row-1 center-x">
  <div class="row">
    <div class="col center-x">
      <h1><?= $this->pageObj->code ?></h1>
    </div>
  </div>

  <div class="row">
    <div class="col f-col g-row-1">
      <div class="row">
        <div class="col center-x">
          <p data-typo="h3"><?= $this->pageObj->message ?></p>
        </div>
      </div>

      <div class="row">
        <div class="col center-x">
          <p>Click <a href="<?= $this->url(REDIRECT) ?>" aria-label="Link to <?= REDIRECT ?> page">here</a> to go back to the <?= REDIRECT ?> page.</p>
        </div>
      </div>
    </div>
  </div>
</section>
