<section class="home f-col g-row-3">
  <div class="row">
    <div class="col f-col g-row-1">
      <div class="row">
        <div class="col">
          <h1 data-typo="h2">Welcome to Simpl!</h1>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <p>An easy-to-use PHP, HTML, Sass and TypeScript framework!</p>
        </div>
      </div>

      <div class="row">
        <a class="col button simpl g-col-0.5 center-y f-0" aria-label="Button to the getting started page" href="https://simpl.iwanvanderwal.nl/getting-started/" target="_blank">
          <i class="fas fa-rocket" aria-hidden="true"></i>Getting started
        </a>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col f-col g-row-0.5">
      <div class="row">
        <div class="col">
          <h3 data-typo="h5">Install add-ons:</h3>
        </div>
      </div>

      <div class="row">
        <div class="col code-block f-row g-col-1 center-y f-0">
          <i class="fa fa-terminal"></i>
          <code><span class="command-name">npx</span> <span class="command-argument">@ijuantm/simpl-addon</span> <span class="command-arguments">--list</span></code>
          <span class="copy-code" title="Click to copy command to clipboard"><i class="fa fa-copy" aria-label="Copy to clipboard"></i></span>
        </div>
      </div>
    </div>
  </div>

  <div class="row g-2">
    <a class="col card center-y" href="https://simpl.iwanvanderwal.nl/docs/" target="_blank" aria-label="Link to the Simpl documentation">
      <div class="row g-col-2">
        <div class="col card-icon center f-0">
          <i class="fas fa-book" aria-hidden="true"></i>
        </div>

        <div class="col f-col g-row-1">
          <div class="row">
            <div class="col">
              <h2 class="card-title" data-typo="h4">Documentation</h2>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <p>Read the documentation for the Simpl framework.</p>
            </div>
          </div>
        </div>
      </div>
    </a>

    <a class="col card center-y" href="https://github.com/IJuanTM/simpl/" target="_blank" aria-label="Link to the Simpl GitHub repository">
      <div class="row g-col-2">
        <div class="col card-icon center f-0">
          <i class="fab fa-github" aria-hidden="true"></i>
        </div>
        <div class="col f-col g-row-1">
          <div class="row">
            <div class="col">
              <h2 class="card-title" data-typo="h4">GitHub</h2>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <p>View the source code on GitHub.</p>
            </div>
          </div>
        </div>
      </div>
    </a>
  </div>
</section>
