<section class="home f-col">
  <div class="row">
    <div class="col center-x">
      <h3>Welcome</h3>
    </div>
  </div>

  <div class="row">
    <div class="col home-info f-col">
      <div class="row">
        <div class="col center-x">
          <p>This is the default landing page for the Simpl framework.</p>
        </div>
      </div>

      <div class="row">
        <div class="col center-x">
          <p>For more information, see the documentation <a href="https://simpl.iwanvanderwal.nl/docs" target="_blank" aria-label="Link to the Simpl documentation">here</a>.</p>
        </div>
      </div>

      <div class="row">
        <div class="col center-x">
          <p>Enjoy using Simpl!</p>
        </div>
      </div>
    </div>
  </div>
</section>
