<?php require_once __DIR__ . '/parts/top.phtml' ?>

<?php require_once __DIR__ . '/parts/header.phtml' ?>

<table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%">
  <tr>
    <td style="padding: 32px 48px;" width="100%">
      <table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%">
        <tr>
          <td style="padding-bottom: 16px; font-family: 'Inter', sans-serif; font-size: 20px; color: white; font-weight: bold;" width="100%">Hello!</td>
        </tr>

        <tr>
          <td style="padding-bottom: 16px; font-family: 'Inter', sans-serif; font-size: 14px; color: white;" width="100%">An account has been created for you by an administrator.</td>
        </tr>

        <tr>
          <td style="padding: 16px 0; font-family: 'Inter', sans-serif; font-size: 14px; color: white;" width="100%">You can log in <a href="<?= $link ?>" style="color: #D01018;">here</a> using the following temporary password:</td>
        </tr>

        <tr>
          <td style="padding-bottom: 16px; font-family: 'Inter', sans-serif; font-size: 14px; color: white; font-weight: bold;" width="100%"><?= $password ?></td>
        </tr>

        <tr>
          <td style="padding: 16px 0; font-family: 'Inter', sans-serif; font-size: 14px; color: white;" width="100%">You will be prompted to change your password upon your first login for security reasons.</td>
        </tr>

        <tr>
          <td style="font-family: 'Inter', sans-serif; font-size: 14px; color: white; font-style: italic" width="100%">If you did not request this account or believe this was sent to you in error, please ignore this email.</td>
        </tr>
      </table>
    </td>
  </tr>
</table>

<?php require_once __DIR__ . '/parts/footer.phtml' ?>

<?php require_once __DIR__ . '/parts/bottom.phtml' ?>
