<?php require_once __DIR__ . '/parts/top.phtml' ?>

<?php require_once __DIR__ . '/parts/header.phtml' ?>

<table border="0" cellpadding="0" cellspacing="0" role="presentation" style="padding: 32px 48px;" width="100%">
  <tr>
    <td style="padding-bottom: 16px; font-family: 'Inter', sans-serif; font-size: 14px; color: white;" width="100%">
      <strong><?= $from ?></strong> &bull; <?= $date ?> <?= $time ?>
    </td>
  </tr>

  <tr>
    <td style="border-bottom:2px solid #D01018; line-height:0; font-size: 0;" width="100%">&nbsp;</td>
  </tr>

  <tr>
    <td style="padding-top: 16px; font-family: 'Inter', sans-serif; font-size: 14px; color: white;">
      <?= $contents ?>
    </td>
  </tr>
</table>

<?php require_once __DIR__ . '/parts/footer.phtml' ?>

<?php require_once __DIR__ . '/parts/bottom.phtml' ?>
