<?php require_once __DIR__ . '/parts/top.phtml' ?>

<?php require_once __DIR__ . '/parts/header.phtml' ?>

<table border="0" cellpadding="0" cellspacing="0" role="presentation" style="padding: 32px 48px;" width="100%">
  <tr>
    <td style="padding-bottom: 16px; font-family: 'Inter', sans-serif; font-size: 14px; color: white;" width="100%">You have requested to reset your password.</td>
  </tr>

  <tr>
    <td style="padding-bottom: 16px; font-family: 'Inter', sans-serif; font-size: 14px; color: white;" width="100%">To reset your password, please click the button below:</td>
  </tr>

  <tr>
    <td>
      <a href="<?= $link ?>" style="display: inline-block; padding: 16px 32px; background-color: #D01018; color: white; text-decoration: none; border-radius: 4px; font-family: 'Inter', sans-serif; font-size: 14px;">Reset password</a>
    </td>
  </tr>

  <tr>
    <td style="padding-top: 16px; font-family: 'Inter', sans-serif; font-size: 14px; color: white; font-style: italic" width="100%">If you did not request a password reset, please ignore this email.</td>
  </tr>
</table>

<?php require_once __DIR__ . '/parts/footer.phtml' ?>

<?php require_once __DIR__ . '/parts/bottom.phtml' ?>
