<?php require_once __DIR__ . '/parts/top.phtml' ?>

<?php require_once __DIR__ . '/parts/header.phtml' ?>

<table border="0" cellpadding="0" cellspacing="0" role="presentation" style="padding: 32px 48px;" width="100%">
  <tr>
    <td style="padding-bottom: 16px; font-family: 'Inter', sans-serif; font-size: 20px; color: white; font-weight: bold;" width="100%">Welcome!</td>
  </tr>

  <tr>
    <td style="padding-bottom: 16px; font-family: 'Inter', sans-serif; font-size: 14px; color: white;" width="100%">Your account has been successfully created!</td>
  </tr>

  <tr>
    <td style="padding-bottom: 16px; font-family: 'Inter', sans-serif; font-size: 14px; color: white;" width="100%">To verify your email address, please click the button below:</td>
  </tr>

  <tr>
    <td>
      <a href="<?= $link ?>" style="display: inline-block; padding: 16px 32px; background-color: #D01018; color: white; text-decoration: none; border-radius: 4px; font-family: 'Inter', sans-serif; font-size: 14px;">Verify email</a>
    </td>
  </tr>

  <tr>
    <td style="padding: 16px 0; font-family: 'Inter', sans-serif; font-size: 14px; color: white;" width="100%">Or manually enter the following code on the verification page:</td>
  </tr>

  <tr>
    <td style="padding-bottom: 16px; font-family: 'Inter', sans-serif; font-size: 20px; color: white; font-weight: bold;" width="100%"><?= $code ?></td>
  </tr>

  <tr>
    <td style="font-family: 'Inter', sans-serif; font-size: 14px; color: white; font-style: italic" width="100%">If you did not create an account, please ignore this email.</td>
  </tr>
</table>

<?php require_once __DIR__ . '/parts/footer.phtml' ?>

<?php require_once __DIR__ . '/parts/bottom.phtml' ?>
