<table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%">
  <tr>
    <td style="padding: 16px 48px; background-color: #141414; border-top: 2px solid #4F4F4F" width="100%">
      <table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%">
        <tr>
          <td>
            <a href="https://simpl.iwanvanderwal.nl" style="color: white; font-family: 'Inter', sans-serif; font-size: 12px; text-decoration: none;">&copy; 2026 Simpl</a>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
