<table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%">
  <tr>
    <td style="padding: 16px 48px; background-color: #141414; border-bottom: 2px solid #4F4F4F" width="100%">
      <table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%">
        <tr>
          <td valign="middle" width="56">
            <img alt="Simpl Logo" height="48" src="https://cdn.simpl.iwanvanderwal.nl/img/svg/simpl.svg" style="display: block;" width="48"/>
          </td>
          <td valign="middle">
            <h1 style="color: white; font-family: 'IBM Plex Sans', sans-serif; font-weight: 700; font-size: 20px; margin: 0">Simpl</h1>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
