<!DOCTYPE html>
<html lang="en">
<head>
  <title><?= htmlspecialchars($title ?? 'Email - ' . APP_NAME) ?></title>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <link href="https://fonts.googleapis.com/css?family=IBM%20Plex%20Sans" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Inter" rel="stylesheet">
</head>
<body style="height: 100%; margin: 0; background-color: #0E0E0E;">
<table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%">
  <tr>
    <td>
