<?php
use app\Controllers\SessionController;
?>

</main>

<!-- Alert -->
<?php if (SessionController::get('alert') !== null) : ?>
  <div class="alert <?= SessionController::get('alert')['type'] ?? '' ?> global" role="alert" data-timeout="<?= isset(SessionController::get('alert')['timeout']) ? (SessionController::get('alert')['timeout'] - time()) * 1000 : 0 ?>">
    <?= SessionController::get('alert')['message'] ?>
  </div>
<?php endif ?>

<!-- Footer -->
<?php $this->part('footer') ?>

<!-- Cookie -->
<?php $this->part('cookie') ?>

<!-- Scripts -->
<?php $this->part('index/js') ?>
</body>
</html>
