<footer>
  <div class="row g-col-1">
    <div class="col center-y">
      <a class="link" href="https://www.iwanvanderwal.nl" target="_blank" aria-label="Link to the portfolio website of the creator">&copy; 2025 Iwan van der Wal</a>
    </div>
    <div class="col center-y end-x">
      <a class="link" href="https://github.com/IJuanTM/simpl" target="_blank" aria-label="Link to the Simpl GitHub repository">Version <?= APP_VERSION ?> (<?= LAST_UPDATE ?>)</a>
    </div>
  </div>
</footer>
