<footer>
  <div class="row">
    <div class="col">
      <a href="https://www.iwanvanderwal.nl" target="_blank" aria-label="Link to the portfolio website of the creator">&copy; 2023 Iwan van der Wal</a>
    </div>
    <div class="col end-x">
      <a href="https://github.com/IJuanTM/simpl" target="_blank" aria-label="Link to the Simpl GitHub repository">Version 1.1.1 (2023-12-20)</a>
    </div>
  </div>
</footer>
