<dialog class="row modal-overlay center invisible" data-user-purge-modal aria-modal="true" aria-label="Purge user">
  <div class="col modal f-col g-row-2">
    <div class="row center-y g-col-1">
      <h3 class="col">Purge user</h3>
      <button class="col link modal-close lh-1 g-col-0.5 center-y f-0" aria-label="Close modal"><i class="fas fa-xmark"></i></button>
    </div>

    <div class="row modal-body">
      <div class="col f-col g-row-1">
        <div class="row">
          <div class="col">
            <p>Are you sure you want to permanently purge this user?</p>
          </div>
        </div>

        <div class="row">
          <div class="col modal-user-info f-col g-row-0.5">
            <div class="row g-col-0.5 center-y">
              <span class="col text-muted f-0">Id:</span>
              <span class="col modal-user-id">-</span>
            </div>
            <div class="row g-col-0.5 center-y">
              <span class="col text-muted f-0">Username:</span>
              <span class="col modal-user-username">-</span>
            </div>
            <div class="row g-col-0.5 center-y">
              <span class="col text-muted f-0">Email:</span>
              <span class="col modal-user-email">-</span>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col">
            <p class="quote warning">Purging a user will permanently remove them from the database, with no way of recovery! Make sure this is really what you want!</p>
          </div>
        </div>
      </div>
    </div>

    <div class="row g-2 center-x">
      <button class="col link modal-close lh-1 g-col-0.5 center-y f-0"><i class="fas fa-xmark"></i>Cancel</button>
      <form class="col modal-purge-form f-0" method="POST" action="">
        <input type="hidden" name="submit" value="1">
        <div class="row">
          <button class="col button purge-user g-col-0.5 center-y f-0" type="submit"><i class="fas fa-skull"></i>Purge user</button>
        </div>
      </form>
    </div>
  </div>
</dialog>
