<dialog class="modal-overlay" data-role-delete-modal aria-label="Delete role">
  <div class="col modal f-col g-row-2">
    <div class="row center-y g-col-1">
      <h3 class="col">Delete role</h3>
      <button class="col link modal-close lh-1 g-col-0.5 center-y f-0" aria-label="Close modal"><i class="fas fa-xmark"></i></button>
    </div>

    <div class="row modal-body">
      <div class="col f-col g-row-1">
        <div class="row">
          <div class="col">
            <p>Are you sure you want to delete this role?</p>
          </div>
        </div>

        <div class="row">
          <div class="col modal-user-info f-col g-row-0.5">
            <div class="row g-col-0.5 center-y">
              <span class="col text-muted f-0">Id:</span>
              <span class="col modal-role-id">-</span>
            </div>
            <div class="row g-col-0.5 center-y">
              <span class="col text-muted f-0">Name:</span>
              <span class="col modal-role-name">-</span>
            </div>
            <div class="row g-col-0.5 center-y">
              <span class="col text-muted f-0">Users:</span>
              <span class="col modal-role-user-count">-</span>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col">
            <p class="quote modal-warning warning hidden"><span class="quote-text modal-warning-text"></span></p>
          </div>
        </div>
      </div>
    </div>

    <div class="row g-2 center-x">
      <button class="col link modal-close lh-1 g-col-0.5 center-y f-0"><i class="fas fa-xmark"></i>Cancel</button>
      <form class="col modal-delete-role-form f-0" method="POST" action="">
        <input type="hidden" name="submit" value="1">

        <div class="row">
          <button class="col button delete-role g-col-0.5 center-y f-0" type="submit"><i class="fas fa-trash"></i>Delete role</button>
        </div>
      </form>
    </div>
  </div>
</dialog>
