<table>
  <tbody>
  <tr>
    <td style="color: #D01018; font-weight: 600; padding-bottom: 8px">Date:</td>
    <td style="padding-bottom: 8px">{{ $date }}</td>
    <td style="padding-bottom: 8px"></td>
    <td style="color: #D01018; font-weight: 600; padding-bottom: 8px">Time:</td>
    <td style="padding-bottom: 8px">{{ $time }}</td>
  </tr>
  <tr>
    <td colspan="5">{{ $contents }}</td>
  </tr>
  <tr>
    <td style="color: #D01018; font-weight: 600; padding-top: 8px">Sender:</td>
    <td style="padding-top: 8px">{{ $from }}</td>
    <td style="padding-top: 8px" colspan="3"></td>
  </tr>
  </tbody>
</table>
