<table>
  <tbody>
  <tr>
    <td style="color: #D01018; font-weight: 600; padding-bottom: 8px">Your account has been successfully created!</td>
  </tr>
  <tr>
    <td>To proceed you have to activate your account.</td>
  </tr>
  <tr>
    <td>Enter the following code on the page you've been redirected to.</td>
  </tr>
  <tr>
    <td style="color: #D01018; font-size: 24px; font-weight: 600; text-align: center; padding: 8px 0">{{ $code }}</td>
  </tr>
  <tr>
    <td>Or follow this link: <a href="{{ $link }}">{{ $link }}</a></td>
  </tr>
  <tr>
    <td style="color: #C8C8C8; font-size: 14px; padding-top: 8px">If you did not create this account you can ignore this mail and delete it.</td>
  </tr>
  </tbody>
</table>
