<?php require_once __DIR__ . '/parts/top.phtml' ?>

<?php require_once __DIR__ . '/parts/header.phtml' ?>

<table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%">
  <tr>
    <td style="padding: 32px 48px;" width="100%">
      <table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%">
        <tr>
          <td style="padding-bottom: 16px; font-family: 'Inter', sans-serif; font-size: 14px; color: white;" width="100%">You have requested to reset your password.</td>
        </tr>

        <tr>
          <td style="padding-bottom: 16px; font-family: 'Inter', sans-serif; font-size: 14px; color: white;" width="100%">To reset your password, please click the button below:</td>
        </tr>

        <tr>
          <td>
            <table border="0" cellpadding="0" cellspacing="0" role="presentation">
              <tr>
                <td align="center" bgcolor="#D01018" style="padding: 16px 32px; border: 2px solid #4F4F4F; border-radius: 8px;">
                  <a href="<?= $link ?>" style="font-family: 'Inter', sans-serif; font-size: 14px; color: #ffffff; text-decoration: none;">Reset password</a>
                </td>
              </tr>
            </table>
          </td>
        </tr>

        <tr>
          <td style="padding-top: 16px; font-family: 'Inter', sans-serif; font-size: 14px; color: white; font-style: italic" width="100%">If you did not request a password reset, please ignore this email.</td>
        </tr>
      </table>
    </td>
  </tr>
</table>

<?php require_once __DIR__ . '/parts/footer.phtml' ?>

<?php require_once __DIR__ . '/parts/bottom.phtml' ?>
