<?php
use app\Controllers\AppController;
require_once __DIR__ . '/parts/top.phtml';
?>

<?php require_once __DIR__ . '/parts/header.phtml' ?>

<table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%">
  <tr>
    <td style="padding: 32px 48px;" width="100%">
      <table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%">
        <tr>
          <td style="padding-bottom: 16px; font-family: 'IBM Plex Sans', sans-serif; font-size: 20px; color: white; font-weight: 700;" width="100%">Your login code</td>
        </tr>

        <tr>
          <td style="padding-bottom: 16px; font-family: 'Inter', sans-serif; font-size: 14px; color: white;" width="100%">Use the code below to finish signing in:</td>
        </tr>

        <tr>
          <td style="padding-bottom: 16px; font-family: 'Inter', sans-serif; font-size: 28px; letter-spacing: 6px; color: white; font-weight: bold;" width="100%"><?= AppController::sanitize($code) ?></td>
        </tr>

        <tr>
          <td style="font-family: 'Inter', sans-serif; font-size: 14px; color: white; font-style: italic" width="100%">If you didn't try to sign in, someone may have your password. Change it as soon as you can.</td>
        </tr>
      </table>
    </td>
  </tr>
</table>

<?php require_once __DIR__ . '/parts/footer.phtml' ?>

<?php require_once __DIR__ . '/parts/bottom.phtml' ?>
