<?php use app\Controllers\FormController; ?>

<section class="reset-password">
  <div class="row center-x">
    <form class="col" method="POST" action="">
      <div class="row">
        <div class="col center-x">
          <h3>Change password</h3>
        </div>
      </div>

      <?= FormController::$alert ?>

      <div class="row">
        <div class="col form-group">
          <div class="row">
            <label class="col" for="old-password">Old password: <span class="required">*</span></label>
            <div class="col password-warning end-x hidden">Caps lock is on!</div>
          </div>
          <div class="row input-group <?= (isset($_POST['submit']) && empty($_POST['new-password'])) ? 'error' : '' ?>">
            <div class="col input-prepend center f-0"><i class="fas fa-key"></i></div>
            <input class="col" id="old-password" type="password" name="old-password" placeholder="Enter old password:" maxlength="50" value="<?= $_POST['old-password'] ?? '' ?>">
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col form-group">
          <div class="row form-row">
            <div class="col form-group">
              <div class="row">
                <label class="col" for="new-password">New password: <span class="required">*</span></label>
                <div class="col password-warning end-x hidden">Caps lock is on!</div>
              </div>
              <div class="row input-group <?= (isset($_POST['submit']) && empty($_POST['new-password'])) ? 'error' : '' ?>">
                <div class="col input-prepend center f-0"><i class="fas fa-key"></i></div>
                <input class="col input-password" id="new-password" type="password" name="new-password" placeholder="Enter new password:" maxlength="50" value="<?= $_POST['new-password'] ?? '' ?>">
                <div class="col input-append center f-0"><i class="fas fa-eye password-toggle"></i></div>
              </div>
            </div>

            <div class="col form-group">
              <div class="row">
                <label class="col" for="new-password-check">Repeat new password: <span class="required">*</span></label>
              </div>
              <div class="row input-group <?= (isset($_POST['submit']) && empty($_POST['new-password-check'])) ? 'error' : '' ?>">
                <div class="col input-prepend center f-0"><i class="fas fa-key"></i></div>
                <input class="col" id="new-password-check" type="password" name="new-password-check" maxlength="50" placeholder="Repeat new password:">
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <p class="form-details">Password must be at least 8 characters long, and contain at least one uppercase letter, one lowercase letter and one number.</p>
            </div>
          </div>
        </div>
      </div>

      <div class="row button-row center-x">
        <button class="col center-y f-0" type="submit" name="submit" aria-label="Button to submit change password form"><i class="fas fa-lock"></i>Change password</button>
      </div>
    </form>
  </div>
</section>
