<?php
use app\Controllers\AuthController;
use app\Controllers\FormController;
?>

<section class="reset-password">
  <div class="row center-x">
    <form class="col g-row-2" method="POST" action="">
      <div class="row">
        <div class="col center-x">
          <h1 data-typo="h2">Change password</h1>
        </div>
      </div>

      <?= FormController::formAlerts() ?>

      <div class="row">
        <div class="col form-group g-row-0.5">
          <div class="row">
            <label class="col" for="old-password">Old password: <span class="required">*</span></label>
            <div class="col password-warning end-x hidden">Caps lock is on!</div>
          </div>
          <div class="row input-group <?= (isset($_POST['submit']) && empty($_POST['new-password'])) ? 'error' : '' ?>">
            <div class="col input-prepend center f-0"><i class="fas fa-key"></i></div>
            <input class="col" id="old-password" type="password" name="old-password" maxlength="50" placeholder="Enter old password:" value="<?= $_POST['old-password'] ?? '' ?>" autocomplete="old-password" aria-label="Old password input field">
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col form-group g-row-0.5">
          <div class="row form-row g-1">
            <div class="col form-group g-row-0.5">
              <div class="row">
                <label class="col" for="new-password">New password: <span class="required">*</span></label>
                <div class="col password-warning end-x hidden">Caps lock is on!</div>
              </div>
              <div class="row input-group <?= (isset($_POST['submit']) && empty($_POST['new-password'])) ? 'error' : '' ?>">
                <div class="col input-prepend center f-0"><i class="fas fa-key"></i></div>
                <input class="col input-password" id="new-password" type="password" name="new-password" maxlength="50" placeholder="Enter new password:" value="<?= $_POST['new-password'] ?? '' ?>" autocomplete="new-password" aria-label="New password input field">
                <div class="col input-append center f-0"><i class="fas fa-eye password-toggle"></i></div>
              </div>
            </div>

            <div class="col form-group g-row-0.5">
              <div class="row">
                <label class="col" for="new-password-check">Repeat new password: <span class="required">*</span></label>
              </div>
              <div class="row input-group <?= (isset($_POST['submit']) && empty($_POST['new-password-check'])) ? 'error' : '' ?>">
                <div class="col input-prepend center f-0"><i class="fas fa-key"></i></div>
                <input class="col" id="new-password-check" type="password" name="new-password-check" maxlength="50" placeholder="Repeat new password:" autocomplete="new-password-check" aria-label="Repeat new password input field">
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <p class="form-details"><?= AuthController::getPasswordRequirements() ?></p>
            </div>
          </div>
        </div>
      </div>

      <div class="row g-2 center-x">
        <a class="col link g-col-0.5 center-y f-0" href="<?= $this::prev() ?>"><i class="fas fa-arrow-left"></i>Back</a>
        <button class="col button g-col-0.5 center-y f-0" type="submit" name="submit" aria-label="Button to submit change password form"><i class="fas fa-lock"></i>Change password</button>
      </div>
    </form>
  </div>
</section>
