<?php use app\Controllers\FormController; ?>

<section class="contact">
  <div class="row center-x">
    <form class="col" method="POST" action="">
      <div class="row">
        <div class="col center-x">
          <h3>Contact</h3>
        </div>
      </div>

      <?= FormController::$alert ?>

      <div class="row">
        <div class="col form-group">
          <div class="row">
            <label class="col" for="name">Name: <span class="required">*</span></label>
          </div>
          <div class="row input-group <?= (isset($_POST['submit']) && empty($_POST['name'])) ? 'error' : '' ?>">
            <div class="col input-prepend center f-0"><i class="fas fa-user"></i></div>
            <input class="col" id="name" name="name" placeholder="Enter name:" maxlength="100" value="<?= $_POST['name'] ?? '' ?>">
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col form-group">
          <div class="row">
            <label class="col" for="email">Email: <span class="required">*</span></label>
          </div>
          <div class="row input-group <?= (isset($_POST['submit']) && empty($_POST['email'])) ? 'error' : '' ?>">
            <div class="col input-prepend center f-0"><i class="fas fa-at"></i></div>
            <input class="col" id="email" type="email" name="email" placeholder="Enter email:" maxlength="100" value="<?= $_POST['email'] ?? '' ?>">
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col form-group">
          <div class="row">
            <label class="col" for="subject">Subject: <span class="required">*</span></label>
          </div>
          <div class="row input-group <?= (isset($_POST['submit']) && empty($_POST['subject'])) ? 'error' : '' ?>">
            <div class="col input-prepend center f-0"><i class="fas fa-heading"></i></div>
            <input class="col" id="subject" name="subject" placeholder="Enter subject:" maxlength="100" value="<?= $_POST['subject'] ?? '' ?>">
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col form-group">
          <div class="row">
            <label class="col" for="message">Message: <span class="required">*</span></label>
            <div class="col end-x end-y">
              <p class="form-link clear-message" inert>Clear</p>
            </div>
          </div>
          <div class="row input-group <?= (isset($_POST['submit']) && empty($_POST['message'])) ? 'error' : '' ?>">
            <div class="col input-prepend center f-0"><i class="fas fa-message"></i></div>
            <textarea class="col message-field" id="message" name="message" placeholder="Enter message:" rows="5" maxlength="1000"><?= $_POST['message'] ?? '' ?></textarea>
          </div>
          <div class="row">
            <div class="col">
            </div>
            <div class="col end-x">
              <p class="form-details message-warning"><span class="message-length">0</span>/1000</p>
            </div>
          </div>
        </div>
      </div>

      <div class="row button-row center-x">
        <button class="col center-y f-0" type="submit" name="submit" aria-label="Button to submit the contact form"><i class="fas fa-paper-plane"></i>Send</button>
      </div>
    </form>
  </div>
</section>
