<?php use app\Controllers\FormController; ?>

<section class="forgot-password">
  <div class="row center-x">
    <form class="col" method="POST" action="">
      <div class="row">
        <div class="col center-x">
          <h3>Forgot password</h3>
        </div>
      </div>

      <?= FormController::$alert ?>

      <div class="row">
        <div class="col">
          <p class="form-details">In case you forgot your password, we can send you a link to reset it. Enter your email address below and we'll send you a link to reset your password.</p>
        </div>
      </div>

      <div class="row">
        <div class="col form-group">
          <div class="row">
            <label class="col" for="email">Email: <span class="required">*</span></label>
          </div>
          <div class="row input-group <?= (isset($_POST['submit']) && empty($_POST['email'])) ? 'error' : '' ?>">
            <div class="col input-prepend center f-0"><i class="fas fa-at"></i></div>
            <input class="col" id="email" type="email" name="email" placeholder="Enter email:" value="<?= $_POST['email'] ?? '' ?>">
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <p class="form-details">It may take a few minutes for the email to arrive. If you don't see it in your inbox, check your spam folder.</p>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <p class="form-details">Didn't receive an email? Please try again after 1 minute or contact an administrator.</p>
        </div>
      </div>

      <div class="row button-row center-x">
        <button class="col center-y f-0" type="submit" name="submit" aria-label="Button to submit the forgot password form" data-timeout="<?= isset($_SESSION['timeout']) ? ($_SESSION['timeout'] - time()) * 1000 : 0 ?>" inert><i class="fas fa-key"></i>Forgot password</button>
      </div>
    </form>
  </div>
</section>
