<?php
use app\Controllers\AuthController;
use app\Controllers\FormController;
use app\Models\Url;
?>

<section class="row register center-x">
  <form class="col g-row-2" method="POST" action="">
    <div class="row">
      <div class="col center-x">
        <h1 data-typo="h2">Register</h1>
      </div>
    </div>

    <?= FormController::formAlerts() ?>

    <div class="row">
      <div class="col form-group g-row-0.5">
        <div class="row">
          <label class="col" for="email">Email: <span class="required">*</span></label>
        </div>
        <div class="row input-group <?= (isset($_POST['submit']) && empty($_POST['email'])) ? 'error' : '' ?>">
          <div class="col input-prepend center f-0"><i class="fas fa-at"></i></div>
          <input class="col" id="email" type="email" name="email" maxlength="100" placeholder="Enter email:" value="<?= $_POST['email'] ?? '' ?>" autocomplete="email" aria-label="Email input field">
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col form-group g-row-0.5">
        <div class="row form-row g-1">
          <div class="col form-group g-row-0.5">
            <div class="row">
              <label class="col" for="password">Password: <span class="required">*</span></label>
              <div class="col password-warning end-x hidden">Caps lock is on!</div>
            </div>
            <div class="row input-group <?= (isset($_POST['submit']) && empty($_POST['password'])) ? 'error' : '' ?>">
              <div class="col input-prepend center f-0"><i class="fas fa-key"></i></div>
              <input class="col input-password" id="password" type="password" name="password" maxlength="50" placeholder="Enter password:" value="<?= $_POST['password'] ?? '' ?>" autocomplete="new-password" aria-label="Password input field">
              <div class="col input-append center f-0"><i class="fas fa-eye password-toggle"></i></div>
            </div>
          </div>

          <div class="col form-group g-row-0.5">
            <div class="row">
              <label class="col" for="password-check">Repeat password: <span class="required">*</span></label>
            </div>
            <div class="row input-group <?= (isset($_POST['submit']) && empty($_POST['password-check'])) ? 'error' : '' ?>">
              <div class="col input-prepend center f-0"><i class="fas fa-key"></i></div>
              <input class="col" id="password-check" type="password" name="password-check" maxlength="50" placeholder="Repeat password:" autocomplete="new-password-check" aria-label="Repeat password input field">
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col">
            <p class="form-details"><?= AuthController::getPasswordRequirements() ?></p>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <p class="form-details">Already have an account? <a class="link underline" href="<?= Url::to('login') ?>" aria-label="Link to login page">Click here to login</a>.</p>
      </div>
    </div>

    <div class="row g-2 center-x">
      <button class="col button g-col-0.5 center-y f-0" type="submit" name="submit" aria-label="Button to submit register form"><i class="fas fa-user-plus"></i>Register</button>
    </div>
  </form>
</section>
