<?php
use app\Controllers\AuthController;
use app\Controllers\SessionController;
use app\Models\Url;
?>

<?php if (isset($this->urlArr['subpages'][0]) && in_array($this->urlArr['subpages'][0], ['edit', 'delete', 'restore'])) : ?>

  <?php $this->part('users/' . $this->urlArr['subpages'][0]) ?>

<?php else : ?>

  <section class="users f-col g-row-2">
    <div class="row">
      <div class="col center-x">
        <h1 data-typo="h2">Registered users</h1>
      </div>
    </div>

    <div class="row center-x">
      <div class="col users-table f-col g-row-0.5">

        <?php if (count($this->pageObj->users) > $this->pageObj->page * 10) : ?>

          <div class="row table-container">
            <div class="col">
              <table>
                <thead>
                <tr>
                  <th>Id</th>
                  <th>Username</th>
                  <th>Email</th>
                  <th>Role</th>
                  <th>Verified</th>
                  <th>Created at</th>
                  <th>Last updated</th>
                  <th>Is active</th>
                  <th>Deleted at</th>
                  <th>Actions</th>
                </tr>
                </thead>

                <tbody>

                <?php foreach (array_slice($this->pageObj->users, $this->pageObj->page * 10, 10) as $user) : ?>

                  <tr class="<?= !$user['is_active'] ? 'deleted' : '' ?>">
                    <td><?= $user['id'] ?></td>
                    <td><?= $user['username'] ?: '-' ?></td>
                    <td><?= $user['email'] ?></td>
                    <td><?= $user['role'] === 1 ? 'Admin' : 'User' ?></td>
                    <td><?= AuthController::isVerified($user['id']) ? '<i class="fas fa-check"></i>' : '<i class="fas fa-times"></i>' ?></td>
                    <td><?= $user['created_at'] ?></td>
                    <td><?= $user['last_update'] ?></td>
                    <td><?= !$user['is_active'] ? '<i class="fas fa-times"></i>' : '<i class="fas fa-check"></i>' ?></td>
                    <td><?= $user['deleted_at'] ?: '-' ?></td>
                    <?php if ($user['id'] !== SessionController::get('user')['id']) : ?>
                      <td class="row action-row g-col-1 center-y">
                        <?php if ($user['is_active']) : ?>
                          <a class="col table-action f-0" href="<?= Url::to('users/edit?id=' . $user['id']) ?>"><i class="fas fa-pen"></i></a>
                          <a class="col table-action delete f-0" href="<?= Url::to('users/delete?id=' . $user['id']) ?>"><i class="fas fa-trash"></i></a>
                        <?php else : ?>
                          <a class="col table-action restore f-0" href="<?= Url::to('users/restore?id=' . $user['id']) ?>"><i class="fas fa-wrench"></i></a>
                        <?php endif ?>
                      </td>
                    <?php else : ?>
                      <td>-</td>
                    <?php endif ?>
                  </tr>

                <?php endforeach ?>

                </tbody>
              </table>
            </div>
          </div>

          <div class="row action-row g-col-1">
            <div class="col f-0">
              <p><?= ($this->pageObj->page * 10) + 1 ?> - <?= min((($this->pageObj->page + 1) * 10), count($this->pageObj->users)) ?> of <?= count($this->pageObj->users) ?> users</p>
            </div>
            <div class="col users-pagination g-col-1 end-x">
              <a class="users-action" href="<?= Url::to('users?page=' . ($this->pageObj->page - 1)) ?>" <?= $this->pageObj->page > 0 ?: 'inert' ?>><i class="fas fa-chevron-left"></i> Previous</a>
              <a class="users-action" href="<?= Url::to('users?page=' . ($this->pageObj->page + 1)) ?>" <?= $this->pageObj->page < ceil(count($this->pageObj->users) / 10) - 1 ?: 'inert' ?>>Next <i class="fas fa-chevron-right"></i></a>
            </div>
          </div>

        <?php else : ?>

          <div class="row">
            <div class="col">
              <p>No users found.</p>
            </div>
          </div>

        <?php endif ?>

      </div>
    </div>
  </section>

<?php endif ?>
