<!-- Font Awesome -->
<link rel="preload" href="<?= $this->url('lib/Font Awesome/webfonts/fa-brands-400.woff2') ?>" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="<?= $this->url('lib/Font Awesome/webfonts/fa-regular-400.woff2') ?>" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="<?= $this->url('lib/Font Awesome/webfonts/fa-solid-900.woff2') ?>" as="font" type="font/woff2" crossorigin>
